# Generated by Django 3.2.6 on 2021-08-24 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name Sponsor')),
                ('last_name', models.CharField(max_length=20, verbose_name=' Last Name')),
                ('telephone', models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=150, null=True, unique=True, verbose_name='Email')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='Description')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Events')),
            ],
        ),
    ]
