# Generated by Django 3.2.6 on 2021-08-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Events')),
            ],
        ),
    ]
