# Generated by Django 3.2.6 on 2021-08-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name Event')),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=200, null=True, verbose_name='Description')),
                ('url', models.SlugField(default='', unique=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Events')),
            ],
        ),
    ]
